name: pythonProjects
channels:
  - defaults
dependencies:
  - _tflow_select=2.2.0
  - abseil-cpp=20211102.0
  - absl-py=1.4.0
  - aiohttp=3.9.0
  - aiosignal=1.2.0
  - anyio=3.5.0
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=21.4.0
  - babel=2.9.1
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.6.2
  - brotlipy=0.7.0
  - c-ares=1.19.1
  - ca-certificates=2023.08.22
  - cachetools=4.2.2
  - cairo=1.16.0
  - certifi=2023.11.17
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.1.7
  - cryptography=37.0.1
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.9
  - fftw=3.3.9
  - flatbuffers=2.0.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - freetype=2.11.0
  - fribidi=1.0.10
  - frozenlist=1.4.0
  - gast=0.4.0
  - gdk-pixbuf=2.42.8
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.69.1
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.4
  - google-pasta=0.2.0
  - graphite2=1.3.14
  - graphviz=2.50.0
  - grpc-cpp=1.46.1
  - grpcio=1.42.0
  - gts=0.7.6
  - h5py=3.9.0
  - harfbuzz=4.3.0
  - hdf5=1.12.1
  - icu=58.2
  - idna=3.3
  - importlib-metadata=6.0.0
  - intel-openmp=2021.4.0
  - ipykernel=6.15.2
  - ipython=8.4.0
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.0.3
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.16.0
  - jupyter_client=7.3.5
  - jupyter_core=4.10.0
  - jupyter_server=1.18.1
  - jupyterlab=3.4.4
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.12.0
  - keras=2.9.0
  - keras-preprocessing=1.1.2
  - krb5=1.19.4
  - lerc=3.0
  - libcurl=7.84.0
  - libcxx=14.0.6
  - libdeflate=1.8
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.3
  - libgd=2.3.3
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.16
  - libnghttp2=1.46.0
  - libpng=1.6.37
  - libprotobuf=3.20.1
  - librsvg=2.54.4
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libtiff=4.4.0
  - libtool=2.4.6
  - libwebp-base=1.2.2
  - libxml2=2.9.14
  - llvm-openmp=14.0.6
  - lz4-c=1.9.3
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=6.0.4
  - nbclassic=0.3.5
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.5.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - notebook=6.4.12
  - numpy-base=1.22.3
  - oauthlib=3.2.2
  - openssl=1.1.1w
  - opt_einsum=3.3.0
  - packaging=21.3
  - pandocfilters=1.5.0
  - pango=1.50.7
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.2.2
  - pixman=0.40.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.20
  - protobuf=3.20.1
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pydot=1.4.1
  - pygments=2.11.2
  - pyjwt=2.4.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.13
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-flatbuffers=1.12
  - python-graphviz=0.20.1
  - pytz=2022.1
  - pyyaml=6.0.1
  - pyzmq=23.2.0
  - re2=2022.04.01
  - readline=8.1.2
  - requests=2.28.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - send2trash=1.8.0
  - setuptools=63.4.1
  - six=1.16.0
  - snappy=1.1.9
  - sniffio=1.2.0
  - soupsieve=2.3.1
  - sqlite=3.39.3
  - stack_data=0.2.0
  - tensorboard=2.9.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.6.0
  - tensorflow=2.9.1
  - tensorflow-base=2.9.1
  - tensorflow-estimator=2.9.0
  - termcolor=2.1.0
  - terminado=0.13.1
  - testpath=0.6.0
  - tk=8.6.12
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.1.1
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - tzdata=2022c
  - urllib3=1.26.11
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - werkzeug=2.2.3
  - wheel=0.35.1
  - wrapt=1.14.1
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.3
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
      - contourpy==1.0.5
      - cycler==0.11.0
      - fonttools==4.37.4
      - joblib==1.2.0
      - kiwisolver==1.4.4
      - lxml==4.9.1
      - matplotlib==3.6.0
      - numpy==1.23.3
      - pandas==1.5.0
      - pandas-datareader==0.10.0
      - pillow==9.2.0
      - scikit-learn==1.1.2
      - scipy==1.9.1
      - seaborn==0.12.0
      - sklearn==0.0
      - threadpoolctl==3.1.0
      - torch==1.13.0
      - torchaudio==0.13.0
      - torchvision==0.14.0
